### PR TITLE
HAProxy ARTIS instances

### PR DESCRIPTION
**Pull request by Levi990e**
Added Blockscout instance mappings of Artis Tau1 and Sigma1 to the haproxy-config.cfg file.

### CODE REVIEW

**Comment by dforsten** [comment]
All the issues I mentioned above are already resolved in this PR!

**Comment by phahulin** [comment]
Getting these messages:
```
Server artis_sigma1/artis_sigma1 is DOWN, reason: Layer7 wrong status, code: 405, info: "Method Not Allowed", check duration: 350ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
```
and similar ones for artis_sigma1_ws, artis_tau1, artis_tau1_ws.

I'm not sure which request is being sent, probably a health check by haproxy. If it's possbile, could you look it up on your end? Healthchecks should be done by a simple
```
option httpchk GET /
```
but I can't replicate the error

**Comment by phahulin** [comment]
Yes, it's definitely because of the health checks - when I removed the `check` from tau1 backends, they started working https://blockscout.com/artis/tau1

**Comment by Levi990e** [comment]
We found a report about a similar error here: https://discourse.haproxy.org/t/how-to-setup-http-check-for-tcp-backend-in-haproxy/2508  
Since our instances are also using HTTPS, may the addition of `check-ssl` help in our case as well?

**Comment by dforsten** [comment]
@phahulin I have seen there is a new PR (#3) which contains the changes from this PR.
Could you try using "check-ssl" instead of "check" to see if that makes the health checks work without errors please?

**Comment by phahulin** [comment]
Yes, `check-ssl` does work, thank you!
Changes from this PR including ssl-check are included in #3 now, so this one can be closed if you don't have any objections.

**Comment by Levi990e** [comment]
It is fine with us to close this PR.
Have you got an idea when approximately your PR will be merged to master?

**Comment by phahulin** [comment]
> Have you got an idea when approximately your PR will be merged to master?
I don't know when it will be merged because we are still in flow of changing the config for other networks, but your blockscout instances are already available the prod:
https://blockscout.com/artis/tau1
https://blockscout.com/artis/sigma1

**Comment by phahulin** [comment]
> It is fine with us to close this PR.

Could you close this issue please? I don't have enough permissions to do this.

**Comment by dforsten** [comment]
> but your blockscout instances are already available on the prod:
> https://blockscout.com/artis/tau1
> https://blockscout.com/artis/sigma1

Great, thanks!

**Pull request closed without merging**
